services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: loan_management_system
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: your_jwt_secret
      ENV: PRODUCTION

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: loan_management_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
